# Generated by Django 4.2.6 on 2023-11-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
